# Generated by Django 5.0.4 on 2024-06-05 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0007_inscripcionconcurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgresoEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_egreso', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('tipo_egreso', models.CharField(choices=[('pagos', 'Pagos'), ('concurso', 'Concurso')], max_length=50)),
                ('concurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.concurso')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_ingreso', models.CharField(choices=[('donacion', 'Donación'), ('concurso', 'Concurso')], max_length=50)),
                ('concurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.concurso')),
            ],
        ),
        migrations.CreateModel(
            name='PagoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.inscripcionconcurso')),
            ],
        ),
    ]
