# Generated by Django 5.0.4 on 2024-06-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_inscripcionconcurso'),
        ('finanzas', '0002_rename_pagoinscripcion_pagoinscripciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagoInscripciones',
            new_name='PagoInscripcion',
        ),
    ]
