# Generated by Django 5.0.6 on 2024-06-23 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_rename_pagoinscripciones_pagoinscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresoeconomico',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, 'El valor del monto no puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='ingresoeconomico',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, 'El valor del monto no puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='pagoinscripcion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, 'El valor del monto no puede ser negativo.')]),
        ),
    ]
