# Generated by Django 5.0.6 on 2024-06-21 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_proyecto_club'),
        ('proyectos', '0002_proyecto_clubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='clubs',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_asociados', to='clubs.club'),
        ),
    ]
