# Generated by Django 5.0.4 on 2024-05-07 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='nombre',
        ),
    ]
