# Generated by Django 5.0.4 on 2024-05-07 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_first_name_customuser_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'Ingrese solo números.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='semestre',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'El semestre debe ser un número entre 0 y 10'), django.core.validators.MaxValueValidator(10, 'El semestre debe ser un número entre 0 y 10')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'Ingrese solo números.')]),
        ),
    ]
