# Generated by Django 5.0.4 on 2024-05-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('proyectos', '0001_initial'),
        ('tareas', '0001_initial'),
        ('users', '0007_rename_usuarios_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='UsuariosRegistrados',
        ),
    ]
