# Generated by Django 5.0.4 on 2024-06-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('tema_charla', models.CharField(max_length=200)),
                ('biografia', models.TextField()),
                ('imagen', models.ImageField(upload_to='ponentes')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('concurso', 'Concurso'), ('charla', 'Charla')], max_length=20)),
                ('competencia_individual', models.BooleanField(blank=True, null=True)),
                ('max_integrantes', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_inscripcion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ponentes', models.ManyToManyField(blank=True, to='eventos.ponente')),
            ],
        ),
    ]
