# Generated by Django 5.0.4 on 2024-06-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_concurso_remove_ponente_hora_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charla',
            name='tema_charla',
        ),
    ]
