# Generated by Django 5.0.4 on 2024-06-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_remove_charla_hora_fin_remove_charla_hora_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponente',
            name='imagen',
        ),
        migrations.AddField(
            model_name='charla',
            name='imagen',
            field=models.ImageField(default='default_image.jpg', upload_to='charlas'),
        ),
    ]
