# Generated by Django 5.0.4 on 2024-06-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_remove_ponente_imagen_charla_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charla',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='charlas'),
        ),
        migrations.AlterField(
            model_name='ponente',
            name='hora_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ponente',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
    ]
