# Generated by Django 5.0.6 on 2024-06-21 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_inscripcionconcurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionconcurso',
            name='apellido',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Ingrese solo letras para el apellido.')]),
        ),
        migrations.AlterField(
            model_name='inscripcionconcurso',
            name='carrera',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Ingrese solo letras para la carrera.')]),
        ),
        migrations.AlterField(
            model_name='inscripcionconcurso',
            name='cedula',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'La cédula debe tener exactamente 10 dígitos y solo números.')]),
        ),
        migrations.AlterField(
            model_name='inscripcionconcurso',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Ingrese solo letras para el nombre.')]),
        ),
        migrations.AlterField(
            model_name='inscripcionconcurso',
            name='semestre',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, 'El semestre debe ser un número entre 0 y 10'), django.core.validators.MaxValueValidator(10, 'El semestre debe ser un número entre 0 y 10')]),
        ),
        migrations.AlterField(
            model_name='inscripcionconcurso',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe tener exactamente 10 dígitos y solo números.')]),
        ),
        migrations.AlterField(
            model_name='ponente',
            name='apellido',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Ingrese solo letras para el apellido.')]),
        ),
        migrations.AlterField(
            model_name='ponente',
            name='cedula',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'La cédula debe tener exactamente 10 dígitos y solo números.')]),
        ),
        migrations.AlterField(
            model_name='ponente',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Ingrese solo letras para el nombre.')]),
        ),
        migrations.AlterField(
            model_name='ponente',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe tener exactamente 10 dígitos y solo números.')]),
        ),
    ]
