# Generated by Django 5.0.6 on 2024-06-23 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_alter_inscripcionconcurso_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='valor_inscripcion',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, 'El valor de la inscripción no puede ser negativo.')]),
        ),
    ]
