# Generated by Django 5.0.6 on 2024-06-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_inscripcionconcurso_nombre_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionconcurso',
            name='nombre_grupo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
