# Generated by Django 5.0.4 on 2024-06-03 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_charla_tema_charla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charla',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='charla',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='ponente',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='ponente',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
