# Generated by Django 5.0.4 on 2024-06-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_charla_imagen_alter_ponente_hora_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionConcurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('carrera', models.CharField(max_length=100)),
                ('semestre', models.PositiveIntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='eventos.concurso')),
            ],
        ),
    ]
