# Generated by Django 5.0.4 on 2024-06-05 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_inscripcionconcurso'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagoInscripcion',
            new_name='PagoInscripciones',
        ),
    ]
